FROM centos:7

ENV http_proxy %%PROXY_URL%%     # proxy
ENV https_proxy %%PROXY_URL%%    # proxy
ENV no_proxy 127.0.0.1,localhost # proxy

# Install curl, wget, gettext-base(for envsubst)
RUN yum install -y curl wget gettext-base java-11-openjdk-headless \
    && yum clean all

